spring.application.name=gym-crm

storage.data.trainees=src/main/resources/data/trainees.csv
storage.data.trainers=src/main/resources/data/trainers.csv
storage.data.trainings=src/main/resources/data/trainings.csv